### ISSUE TITLE
Stuck on 'downloading patch 1.0.1 to 1.0.2'

### ISSUE THREAD

**Issue by SeanSuttonIAR** [emanzione/PATCH#56]
Downloading individual patches works fine. So if my game is on version 1.0.0 and it pulls the patch to update to 1.0.1 the update happens.

However - when it piggy-backs updates the launcher is forever stuck when downloading the 2nd patch in the series. eg. Stuck on 'downloading patch 1.0.1 to 1.0.2'

So the first of the 2+ patches seem to download, decompress, install. But I never get further than that. The logs tell me almost nothing:
'Applying update 1.0.1_1.0.2 [vL8eRRv7n0FV1z7s9wuQgz8APs8]'

Please advise.

**Comment by emanzione** [comment]
Uhm, if the logs didn't tell anything (errors/warnings, etc), it seems like it's still processing.
You can try to enable the DebugMode to see if the Launcher spits some additional logs to help you understand what's going on.

For how long did you keep it running?

In the past, I've seen a similar situation just once: a customer generated a new update from version X to Y and the algorithm looped (or the computation time was really long) while applying this diff. We didn't understood why (because I wasn't able to reproduce it), but he solved by creating a new build (with additional changes) and a new patch, skipping the problematic version.

Do you mind testing it in an empty project?
